/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: (typeof import('./src/components/FilterSearch/filters/Checkbox.vue'))['default']
    DateRange: (typeof import('./src/components/FilterSearch/filters/DateRange.vue'))['default']
    DragNDropFile: (typeof import('./src/components/DragNDropFile.vue'))['default']
    FilterRow: (typeof import('./src/components/FilterSearch/FilterRow.vue'))['default']
    FilterSearch: (typeof import('./src/components/FilterSearch/FilterSearch.vue'))['default']
    FilterTag: (typeof import('./src/components/FilterSearch/FilterTag.vue'))['default']
    FilterToggle: (typeof import('./src/components/FilterSearch/FilterToggle.vue'))['default']
    FormSteps: (typeof import('./src/components/FormSteps.vue'))['default']
    MAppBarTab: (typeof import('./src/components/MAppBarTab/MAppBarTab.vue'))['default']
    MAppDrawer: (typeof import('./src/components/AppDrawer/MAppDrawer.vue'))['default']
    MButton: (typeof import('./src/components/Button/MButton.vue'))['default']
    MTitleView: (typeof import('./src/components/MTitleView.vue'))['default']
    MFormSteps: (typeof import('./src/components/MFormSteps.vue'))['default']
    MDragNDropFile: (typeof import('./src/components/MDragNDropFile.vue'))['default']
    MultiCheckbox: (typeof import('./src/components/FilterSearch/filters/MultiCheckbox.vue'))['default']
    Range: (typeof import('./src/components/FilterSearch/filters/Range.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SearchBox: (typeof import('./src/components/FilterSearch/SearchBox.vue'))['default']
  }
}
